<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="barrett_hand_mount">
  <xacro:macro name="barrett_hand_mount" params="prefix parent length radius barrett_mount_height barrett_mount_width">
      <link name="${prefix}wrist_load_cell">
	<visual>
	  <material name="ATIGreen">
	    <color rgba="0.4 1.0 0.4 1.0" />
	  </material>
	  <origin xyz= "0 0 0" rpy="0 0 0"/>
	  <geometry>
	    <cylinder length="${length}" radius="${radius}"/>
	  </geometry>
	</visual>
	<collision>
	  <material name="ATIGreen">
	    <color rgba="0.4 1.0 0.4 1.0" />
	  </material>
	  <origin xyz= "0 0 0" rpy="0 0 0"/>
	  <geometry>
	    <cylinder length="${length}" radius="${1.3*radius}"/>
	  </geometry>
	</collision>
	<inertial>
	  <origin xyz="0 0 0" />
	  <mass value="0.50573"/>
	  <inertia
	      ixx="0.0001" ixy="0.0"    ixz="0.0"
	      iyy="0.0001" iyz="0.0"
              izz="0.001"/>
	</inertial>		
      </link>
      <joint name="${prefix}ati_load_cell_joint" type="fixed">
	<origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
	<parent link="${parent}"/>
	<child link="${prefix}wrist_load_cell"/>
      </joint>      

      <link name="${prefix}barrett_mount_link">
	<visual>
	  <origin xyz="0.0 0.02 0" rpy="0 0 0"/>
	  <material name="ATIGreen">
	    <color rgba="0.4 1.0 0.4 1.0" />
	  </material>
	  <geometry>
	    <box size="${0.8*barrett_mount_width} ${barrett_mount_width} ${barrett_mount_height}"/>
	  </geometry>
	</visual>
	<collision>
	  <origin xyz="0.0 0.02 0" rpy="0 0 0"/>
	  <material name="ATIGreen">
	    <color rgba="0.4 1.0 0.4 1.0" />
	  </material>
	  <geometry>
	    <cylinder length="${length}" radius="${1.3*radius}"/>
	  </geometry>
	</collision>
	<inertial>
	  <origin xyz="0 0 0" />
	  <mass value="0.50573"/>
	  <inertia
	      ixx="0.0001" ixy="0.0"    ixz="0.0"
	      iyy="0.0001" iyz="0.0"
              izz="0.001"/>
	</inertial>	
	
	
      </link>
      <joint name="${prefix}barrett_mount_joint" type="fixed">
	<origin xyz="0 0 ${length - barrett_mount_height/2}" rpy="${hand_rpy_offset}"/>
	<parent link="${parent}"/>
	<child link="${prefix}barrett_mount_link"/>
      </joint>


      <link name="${prefix}approach_tran">
	<inertial>
	  <origin xyz="0 0 0" />
	  <mass value="0.001"/>
	  <inertia
	      ixx="0.0001" ixy="0.0"    ixz="0.0"
	      iyy="0.0001" iyz="0.0"
              izz="0.001"/>
	</inertial>
      </link>

      
      <joint name="${prefix}approach_tran_joint" type="fixed">
	<origin xyz="${palm_xyz_offset}" rpy="${palm_rpy_offset}"/>
	<parent link="${parent}"/>
	<child link="${prefix}approach_tran"/>
      </joint>


      
  </xacro:macro>


</robot>
